#!/bin/zsh
# =============================================================================
# modules/mod_log_manager.sh — Log file manager
# NOT included in go sequence — call explicitly with: ./brew_manager.sh log
# Manages session logs in logs/ directory.
# =============================================================================

_module_log() {
    echo ""
    _hline "─" "$C_GRAY"
    echo -e "${C_PURPLE_B}  Log Manager${NC}"
    _hline "─" "$C_GRAY"

    local logs_dir="$BREW_MANAGER_SCRIPT_DIR/logs"
    mkdir -p "$logs_dir"

    echo ""
    echo -e "  ${C_CYAN_B}About this module:${NC}"
    _about_risk "log"
    echo ""
    echo -e "  ${C_GRAY}Manages all log files generated by brew-manager in the logs/ directory.${NC}"
    echo -e "  ${C_GRAY}Session logs are created automatically every time brew_manager.sh runs.${NC}"
    echo ""
    printf "  ${C_CYAN_B}${SYM_INFO}${NC}  ${C_GRAY}%-18s${NC}  %s\n" "brew_report_*"       "Full session logs — one per run of brew_manager.sh"
    printf "  ${C_GREEN}${SYM_OK}${NC}  ${C_GRAY}%-18s${NC}  %s\n"  "agent_stdout_*"     "stdout from LaunchAgent scheduled runs"
    printf "  ${C_YELLOW}${SYM_WARN}${NC}  ${C_GRAY}%-18s${NC}  %s\n" "agent_stderr_*"     "stderr from LaunchAgent runs — errors and warnings"
    echo ""
    echo -e "  ${C_GRAY}This module is never included in go — call it explicitly with: ./brew_manager.sh log${NC}"
    _hline "·" "$C_GRAY"

    # ── Helper: list logs ──
    _list_logs() {
        setopt nullglob
        local _all_logs=("$logs_dir"/*.log)
        unsetopt nullglob

        if (( ${#_all_logs[@]} == 0 )); then
            echo ""
            _info "No log files found in $logs_dir"
            return 1
        fi

        echo ""
        echo -e "  ${C_CYAN_B}Available logs:${NC}"
        echo ""
        printf "  ${C_GRAY}%-4s  %-42s  %-12s  %s${NC}\n" "No." "Filename" "Size" "Date"
        printf "  ${C_GRAY}%-4s  %-42s  %-12s  %s${NC}\n" "────" "──────────────────────────────────────────" "────────────" "──────────────────"

        local _idx=1
        for _lf in "${_all_logs[@]}"; do
            local _name="$(basename "$_lf")"
            local _size="$(du -sh "$_lf" 2>/dev/null | cut -f1)"
            local _date="$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "$_lf" 2>/dev/null)"
            # Color by type
            local _color="$C_WHITE"
            local _sym="$SYM_DOT"
            if [[ "$_name" == brew_report_* ]]; then
                _color="$C_CYAN_B"; _sym="$SYM_INFO"
            elif [[ "$_name" == agent_stdout_* ]]; then
                _color="$C_GREEN"; _sym="$SYM_OK"
            elif [[ "$_name" == agent_stderr_* ]]; then
                _color="$C_YELLOW"; _sym="$SYM_WARN"
            elif [[ "$_name" == scheduler_* ]]; then
                _color="$C_PURPLE_B"; _sym="$SYM_LOCK"
            fi
            printf "  ${C_CYAN_B}[%s]${NC}  ${_color}${_sym}${NC}  ${C_WHITE}%-40s${NC}  ${C_GRAY}%-12s${NC}  ${C_GRAY}%s${NC}\n" \
                "$_idx" "$_name" "${_size:-—}" "${_date:-—}"
            (( _idx++ ))
        done
        echo ""
        return 0
    }

    # ── Main menu loop ──
    while true; do
        _list_logs
        echo -e "  ${C_WHITE}What do you want to do?${NC}"
        echo ""
        printf "  ${C_CYAN_B}%-4s${NC}  ${C_WHITE}%-14s${NC}  ${C_GRAY}%s${NC}\n" \
            "[v]" "View log"      "Print contents of a log file"
        printf "  ${C_RED}%-4s${NC}  ${C_WHITE}%-14s${NC}  ${C_GRAY}%s${NC}\n" \
            "[d]" "Delete"        "Delete one or more logs (e.g. 1,2,3 or all)"
        printf "  ${C_YELLOW}%-4s${NC}  ${C_WHITE}%-14s${NC}  ${C_GRAY}%s${NC}\n" \
            "[p]" "Purge old"     "Delete session logs older than N days"
        printf "  ${C_GRAY}%-4s${NC}  ${C_WHITE}%-14s${NC}  ${C_GRAY}%s${NC}\n" \
            "[n]" "Exit"          "Leave this module"
        echo ""
        printf "  ${C_CYAN}${SYM_ARR}${NC}  Choice ${C_GRAY}[default: n]${NC}: "
        read -r log_choice

        case "${log_choice:-n}" in

            v|V)
                setopt nullglob
                local _vl=("$logs_dir"/*.log)
                unsetopt nullglob
                (( ${#_vl[@]} == 0 )) && _warn "No logs to view" && continue
                echo ""
                printf "  ${C_CYAN}${SYM_ARR}${NC}  Log number to view: "
                read -r _vidx
                _vidx=$(echo "$_vidx" | tr -d ' \t')
                local _vfile="${_vl[$_vidx]}"
                if [[ ! -f "$_vfile" ]]; then _warn "Invalid selection — enter a number from the list"; continue; fi
                echo ""
                echo -e "  ${C_CYAN_B}$(basename "$_vfile")${NC}"
                _hline "·" "$C_GRAY"
                while IFS= read -r line; do
                    echo -e "  ${C_GRAY}${line}${NC}"
                done < "$_vfile"
                _hline "·" "$C_GRAY"
                echo ""
                ;;

            d|D)
                setopt nullglob
                local _dl=("$logs_dir"/*.log)
                unsetopt nullglob
                (( ${#_dl[@]} == 0 )) && _warn "No logs to delete" && continue
                echo ""
                printf "  ${C_CYAN}${SYM_ARR}${NC}  Log number(s) to delete ${C_GRAY}[e.g. 1 or 1,3 or all]${NC}: "
                read -r _didx_raw

                declare -a _to_del=()
                case "${_didx_raw:-}" in
                    all|ALL)
                        for (( _di=1; _di<=${#_dl[@]}; _di++ )); do
                            _to_del+=("$_di")
                        done
                        ;;
                    *)
                        IFS=',' read -rA _didx_parts <<< "$_didx_raw"
                        for _dp in "${_didx_parts[@]}"; do
                            _dp=$(echo "$_dp" | tr -d ' ')
                            [[ "$_dp" =~ ^[0-9]+$ ]] && _to_del+=("$_dp")
                        done
                        ;;
                esac

                if (( ${#_to_del[@]} == 0 )); then _warn "Invalid selection"; continue; fi

                if (( BREW_MANAGER_DRY_RUN )); then
                    _info "Dry-run — would delete ${#_to_del[@]} log(s)"
                    continue
                fi

                local _del_count=0
                for _di in "${_to_del[@]}"; do
                    local _df="${_dl[$_di]}"
                    if [[ -f "$_df" ]]; then
                        rm -f "$_df"
                        _ok "Deleted: $(basename "$_df")"
                        (( _del_count++ ))
                    else
                        _warn "[$_di] not found — skipped"
                    fi
                done
                echo ""
                _stat_row "Logs deleted" "$_del_count" "$C_GREEN_B"
                ;;

            p|P)
                echo ""
                printf "  ${C_CYAN}${SYM_ARR}${NC}  Delete logs older than how many days ${C_GRAY}[default: 30]${NC}: "
                read -r _days
                _days="${_days:-30}"
                if (( BREW_MANAGER_DRY_RUN )); then
                    _info "Dry-run — would purge logs older than ${_days} days"
                    continue
                fi
                local _purge_count=0
                setopt nullglob
                local _pl=("$logs_dir"/*.log)
                unsetopt nullglob
                for _pf in "${_pl[@]}"; do
                    local _age=$(( ( $(date +%s) - $(stat -f %m "$_pf" 2>/dev/null || echo 0) ) / 86400 ))
                    if (( _age > _days )); then
                        rm -f "$_pf"
                        _ok "Purged: $(basename "$_pf") (${_age}d old)"
                        (( _purge_count++ ))
                    fi
                done
                echo ""
                if (( _purge_count == 0 )); then
                    _ok "No logs older than ${_days} days found"
                else
                    _stat_row "Logs purged" "$_purge_count" "$C_GREEN_B"
                fi
                ;;

            n|N|*)
                _info "Exiting log manager"
                break
                ;;
        esac
    done
}
